name: Deploy Vite Project to GitHub Pages

# 👇 Trigger this workflow every time you push to main
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub gives you a free Linux server

    steps:
      # 1️⃣ Get your code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js so we can run npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: portfolio/package-lock.json

      # 3️⃣ Install dependencies from package.json (in portfolio folder)
      - name: Install dependencies
        run: npm ci
        working-directory: portfolio

      # 4️⃣ Build the Vite project (output goes into dist/)
      - name: Build project
        run: npm run build
        working-directory: portfolio
        env:
          NODE_ENV: production

      # 5️⃣ Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 6️⃣ Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./portfolio/dist

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2